# Generated by Django 4.1.2 on 2022-10-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='user',
            new_name='user_id',
        ),
    ]
