# Generated by Django 4.1.2 on 2022-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resetpasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
